# Note this users version 2.1 which means it requires docker-compose 1.9
#
# Usage:
#   docker-compose up --force-recreate
version: '2.1'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 4444:4444
      - 5555:5555
    command: >
      start --chromeContainers 1
            --firefoxContainers 0
            --maxDockerSeleniumContainers 8
            --screenWidth 1930 --screenHeight 1090
            --timeZone "Europe/Berlin"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
    environment:
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      # For OSX remember to include the docker version
      # allowed values are: 1.11 or 1.12 or 1.13
      # - DOCKER=1.11
      # but leave empty for latest or in general for docker >= 17.03.0

  # Feel free to add your services but remember
  # to put them on the same network as Zalenium e.g.
  #
  # postgres:
  #   image: postgres:9.4
  #   container_name: postgres
  #   depends_on:
  #     - zalenium
  #   network_mode: "service:zalenium"
  #   mem_limit: 1g
